services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: monitoring_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-monitoring_agent}
      POSTGRES_USER: ${POSTGRES_USER:-agent_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-agent_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    networks:
      - monitoring_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-agent_user} -d ${POSTGRES_DB:-monitoring_agent}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI Server
  server:
    build: ./server
    container_name: monitoring_server
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-agent_user}:${POSTGRES_PASSWORD:-agent_password}@postgres:5432/${POSTGRES_DB:-monitoring_agent}
      HOST: 0.0.0.0
      PORT: 8000
      LOG_LEVEL: INFO
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - monitoring_network
    volumes:
      - ./server:/app
      - ./logs:/app/logs

volumes:
  postgres_data:
    driver: local

networks:
  monitoring_network:
    driver: bridge
